[package]
name = "paper-benchmark"
version = "1.3.8"
edition = "2024"
license = "AGPL-3.0"
description = "A CLI tool for benchmarking PaperCache."
repository = "https://github.com/griffinandrew/paper-benchmark-cxl.git"
branch = "cxl_sim_exp"
readme = "README.md"
homepage = "https://papercache.io"
keywords = ["caching", "PaperCache"]
categories = ["caching"]

[dependencies]
#paper-client = "1.10.1"
kwik = "1.18.6"
clap = { version = "4.5.40", features = ["derive"] }
byteorder = "1.5.0"
crossbeam-channel = "0.5.15"
statrs = "0.18.0"
spin_sleep = "1.3.2"
libc = "0.2.186"


[features]
allocator_api = []
default = []
all_dram = []
original = []
hot_fix = []
pmem_region_alloc = []
bump_alloc = []
devdax_bump = []
umf = []
value_dram = []
daxpmem = []
hybrid= []
hybrid_lfu = []
hybrid_2q = []
hybrid_fifo = []
hybrid_lru_sized = []
hybrid_s3_fifo = []
hybrid_2q_ghost = []
hybrid_s3_fifo_ghost = []
hybrid_s3_fifo_ghost_lazy_demotion = []
hybrid_s3_fifo_ghost_lazy_demotion_fast_admission = []
hybrid_s3_fifo_ghost_lazy_demotion_fast_admission_midpoint = []
hybrid_s3_fifo_lazy_demotion_fast_admission_midpoint_reprieve = []
hybrid_s3_fifo_lazy_demotion_fast_admission_reprieve = []
hybrid_s3_fifo_lazy_demotion_reprieve = []
hybrid_s3_fifo_lazy_demotion_fast_admission_split_slow_reprieve = []

[dependencies.paper-cache]
path = "/home/griff/work/paper-cache-cxl"

#git = "ssh://git@github.com/griffinandrew/paper-cache-cxl.git"

#branch = "libcache8-testing"

#branch = "libcache8-hardlimit"

#branch = "libcache8-claude"
#branch = "generics-unification"
#branch = "investigate-key-pmem-value-pmem-set-regression"

#features=["all_dram"]

#features=["lfu_hybrid_cache"]

#features=["key_value_pmem"]

#features=["all_dram"]

#features=["all_dram"]

#features = ["key_pmem_value_pmem"]

#features = ["key_value_pmem"]

#features = ["hashbrown_dram"]
features = ["all_dram"]
#features = ["s3_fifo_lazy_demotion_fast_admission_reprieve_hybrid_cache"]

#features = ["global_hashtable_pmem"]

#features = ["all_dram","pmem_region_alloc"]

#features = ["all_dram", "devdax_bump", "eviction_stacks_pmem"]


#features = ["tiering"]

#features = ["multitiering"]

#features = ["all_dram"]

#features = ["all_dram", "pmem_region_alloc"]

#features = ["key_pmem_value_pmem"]

#features = ["key_pmem_value_pmem", "devdax_bump"]

#features = ["all_dram", "eviction_stacks_pmem"]


#features = ["all_dram", "eviction_stacks_pmem", "region_hybrid_allocator"]

#features = ["key_value_pmem","enable_tiering_manager","eviction_stacks_pmem","global_hashtable_pmem"]

#features = ["global_hashtable_pmem","eviction_stacks_pmem"]

#features = ["key_value_pmem","enable_tiering_manager","hashtable_tiering","sets_dram"]

#features = ["enable_tiering_manager","eviction_stacks_pmem","key_value_pmem"]

#features = ["enable_tiering_manager","key_value_pmem"]

#features = ["key_value_pmem", "eviction_stacks_pmem"]


#features = ["multitiering", "key_value_pmem"]

#features = ["global_hashtable_pmem"]
#features = ["key_value_pmem"]
#features = ["all_dram"]

#features = ["key_value_pmem", "devdax_bump"]

#features = ["global_hashtable_pmem", "devdax_bump"]
#features = ["hashbrown_dram"]

#features = ["eviction_stack_pmem" , "hashbrown_dram"]


#features = ["hw_perf_counters", "hashbrown_dram"]
#features = ["hw_perf_counters", "global_hashtable_pmem"]

#features = ["global_flatmap_pmem"]


#features = [ "all_dram"]

#features = ["global_flatmap_dram", "all_dram"]

#features = ["global_flatmap_dram", "all_dram" , "hw_perf_counters"]

#features = ["global_flatmap_pmem", "hw_perf_counters"]

#features = ["key_value_pmem","enable_tiering_manager","hashtable_tiering"]


#features = ["key_value_pmem","enable_tiering_manager"]

#features = ["flatmap_hash_and_object_tiering", "enable_tiering_manager", "key_value_pmem" ]

#[profile.release]
#debug = true
#frame-pointer = "always"


#[build]
#rustflags = ["-C", "force-frame-pointers=yes"]

